"""
HoopsHype Live — Configuration
Edit this file to customize your broadcast.
"""

# ═══════════════════════════════════════
# BLUESKY FEED
# ═══════════════════════════════════════

# Bluesky accounts to pull posts from (handle format)
# 365 curated NBA reporters, analysts, and team accounts
BLUESKY_ACCOUNTS = [
    "ejelite1.bsky.social",
    "yoleo.bsky.social",
    "reichten.bsky.social",
    "drew-h-stevens.bsky.social",
    "tylerparker.bsky.social",
    "danielle-lerner.bsky.social",
    "zackcox.bsky.social",
    "cbergin.bsky.social",
    "youngnba.bsky.social",
    "gameinjurydoc.bsky.social",
    "kerryeggers.bsky.social",
    "ezhoops.bsky.social",
    "patricksandusky.bsky.social",
    "nbaplaydb.bsky.social",
    "granthughes.bsky.social",
    "dillonreagan.bsky.social",
    "gxjones.bsky.social",
    "dallasmavs.bsky.social",
    "sixersnba.bsky.social",
    "trailblazers.bsky.social",
    "nba.com",
    "bweisel.bsky.social",
    "sunsphx.bsky.social",
    "ecreates88.bsky.social",
    "lakerfilmroom.bsky.social",
    "kalidrafts.bsky.social",
    "zenakeita.bsky.social",
    "ethanjskolnick.bsky.social",
    "wolstat.bsky.social",
    "alexaphilippou.bsky.social",
    "chrisbhaynes.bsky.social",
    "mattgeorgesac.bsky.social",
    "bryanfonseca.bsky.social",
    "nbagamereport.bsky.social",
    "shrikhalpada.dev",
    "sethwalder.bsky.social",
    "stepbackstats.bsky.social",
    "mattbolanos.bsky.social",
    "taylorsnarr.bsky.social",
    "hoopsanalyst.bsky.social",
    "thinkingbasketball.bsky.social",
    "deanolytics.bsky.social",
    "dataandme.bsky.social",
    "nateduncannba.bsky.social",
    "beilby.bsky.social",
    "jared-greenberg.bsky.social",
    "aop-nba.bsky.social",
    "mikedsykes.bsky.social",
    "plottheball.com",
    "klaytheist.bsky.social",
    "protectedpick.bsky.social",
    "nba.bankbryan.com",
    "flagrantmag.com",
    "crumpledjumper.bsky.social",
    "bmarksespn.bsky.social",
    "nbcswarriors.bsky.social",
    "johnzannis.bsky.social",
    "toni-vidal.bsky.social",
    "sradjoker.cc",
    "nathanfogg.bsky.social",
    "damichaelcole.bsky.social",
    "aaronbruski.bsky.social",
    "krisplashed.bsky.social",
    "ohnohedidnt24.bsky.social",
    "zachkram.bsky.social",
    "chelneyandrew.bsky.social",
    "mattevanscu.bsky.social",
    "rohankatti.gspn.info",
    "christianclark3.bsky.social",
    "dlocke09.bsky.social",
    "wesgoldberg.bsky.social",
    "drewhilldailym.bsky.social",
    "asherrodblakely.bsky.social",
    "celticsclns.bsky.social",
    "gilsarena.bsky.social",
    "kingjosiah54.bsky.social",
    "jessbenson.bsky.social",
    "sportsmediawatch.bsky.social",
    "kbadenhausen.bsky.social",
    "gwashburnglobe.bsky.social",
    "jeremywoo.bsky.social",
    "daltonjohnson.bsky.social",
    "alexregla.bsky.social",
    "bobbykrivitsky.bsky.social",
    "grant2will.bsky.social",
    "kml7.bsky.social",
    "draftexpress.bsky.social",
    "rodboone.bsky.social",
    "chasedcsports.bsky.social",
    "freemanjoe.bsky.social",
    "bonniesgmwoj.bsky.social",
    "jbeede.bsky.social",
    "notoriousohm.bsky.social",
    "alexgoldennba.bsky.social",
    "positiveresidual.com",
    "tntsportsus.bsky.social",
    "dustindopirak.bsky.social",
    "scottagness.bsky.social",
    "gabriel1200.bsky.social",
    "basketballpoetry.com",
    "kevinoconnornba.bsky.social",
    "ushernba.bsky.social",
    "anpatt7.bsky.social",
    "danielolinger.bsky.social",
    "craigbirnbach.bsky.social",
    "ruhlmuk.bsky.social",
    "sportsreiter.bsky.social",
    "sheacarlson.bsky.social",
    "jgsiegel.bsky.social",
    "morganragan.bsky.social",
    "fmaddennba.bsky.social",
    "chrisherrington.bsky.social",
    "stevejones20.bsky.social",
    "jeffschultzatl.bsky.social",
    "mattbonner.bsky.social",
    "statitudes.com",
    "williamlou.bsky.social",
    "danwolken.bsky.social",
    "garyparrishcbs.bsky.social",
    "tybatiste.bsky.social",
    "davidaldridgedc.bsky.social",
    "jaredweissnba.bsky.social",
    "detnewsrodbeard.bsky.social",
    "nbaoginsa.bsky.social",
    "smithraptorsbeat.bsky.social",
    "shotdrjr.bsky.social",
    "joemussatto.bsky.social",
    "pakaflocka.bsky.social",
    "rickyodonn.bsky.social",
    "joevardon.bsky.social",
    "matthewtynan.bsky.social",
    "christopherhine.bsky.social",
    "jeffzillgitt.bsky.social",
    "williamslaurenl.bsky.social",
    "stevepopper.bsky.social",
    "andrewschlecht.bsky.social",
    "kellyiko.bsky.social",
    "bbstats.bsky.social",
    "thompsonscribe.bsky.social",
    "anthonyvslater.bsky.social",
    "jwquick.bsky.social",
    "grantafseth.bsky.social",
    "patbenson.bsky.social",
    "joeymistretta.bsky.social",
    "tomorsborn.bsky.social",
    "automaticnba.bsky.social",
    "stathead.com",
    "pompeyonsixers.bsky.social",
    "samcyip.bsky.social",
    "havlicekstoleit.bsky.social",
    "jackmack12.bsky.social",
    "montepoole.bsky.social",
    "matsonj.com",
    "celticsblog.bsky.social",
    "jonathanfeigen.bsky.social",
    "kevding.bsky.social",
    "trevorlanenba.bsky.social",
    "benalamar.bsky.social",
    "levakabas.bsky.social",
    "sportinfo247.bsky.social",
    "craftednba.bsky.social",
    "dannychau.bsky.social",
    "inpredict.bsky.social",
    "sbondynba.bsky.social",
    "katywinge.bsky.social",
    "nbastat.bsky.social",
    "apooch.bsky.social",
    "mcnuttmonica.bsky.social",
    "bball-index.bsky.social",
    "timbontemps.bsky.social",
    "cyroasseo.bsky.social",
    "jkylemann.bsky.social",
    "isaaclevyrubinett.bsky.social",
    "bigwos.bsky.social",
    "bellraja19.bsky.social",
    "adamaaronson.bsky.social",
    "purehoop.bsky.social",
    "bengolliver.bsky.social",
    "nickvanexit.bsky.social",
    "juliapoe.bsky.social",
    "aaronjfentress.bsky.social",
    "bballbreakdown.bsky.social",
    "tommybeernba.bsky.social",
    "bykevinclark.bsky.social",
    "legionhoops.bsky.social",
    "ginamizell.bsky.social",
    "calderh.bsky.social",
    "caitlinmaycooper.bsky.social",
    "carmichaeldave.bsky.social",
    "sichrismannix.bsky.social",
    "jadande.bsky.social",
    "treykerby.bsky.social",
    "tasmelas.bsky.social",
    "jeskeets.bsky.social",
    "ramonaespn.bsky.social",
    "espo.bsky.social",
    "kyledrapertv.bsky.social",
    "landonbuford.bsky.social",
    "ericpincus.bsky.social",
    "fredkatz.bsky.social",
    "salmanalinba.bsky.social",
    "pilarcasadobiesa.bsky.social",
    "bannedmacmahon.bsky.social",
    "theoquintard.bsky.social",
    "prohoopswriters.bsky.social",
    "jmcdonaldsa.bsky.social",
    "markjonesespn.bsky.social",
    "flybyknite.bsky.social",
    "blazersedge.bsky.social",
    "jaredgreenberg.bsky.social",
    "dannymarang.bsky.social",
    "jacobrude.bsky.social",
    "r0bato.bsky.social",
    "kambrothers.bsky.social",
    "crainnba.bsky.social",
    "worldwidewob.bsky.social",
    "paolouggetti.bsky.social",
    "deucemason.bsky.social",
    "retepadam.bsky.social",
    "mcuban.bsky.social",
    "andrewmarchand.bsky.social",
    "stevesmith.bsky.social",
    "billsimmons.bsky.social",
    "paulheadleynba.bsky.social",
    "janiscarr2.bsky.social",
    "talkinnba.bsky.social",
    "lakersnation.bsky.social",
    "johnledesma.bsky.social",
    "albertoderoa.bsky.social",
    "jxlorenzi.bsky.social",
    "omarisankofa.bsky.social",
    "bennettdurando.bsky.social",
    "andrewgreif.bsky.social",
    "kellanolson.bsky.social",
    "bytimreynolds.bsky.social",
    "raulbarrigon.bsky.social",
    "tonyreast.bsky.social",
    "coachthorpe.bsky.social",
    "jledwardsiii.bsky.social",
    "jonathanmacri.bsky.social",
    "iztokfranko.bsky.social",
    "alexmcdaniel.co",
    "britishbuzz.bsky.social",
    "lucaskaplan.bsky.social",
    "owenphillips.bsky.social",
    "coupnba.bsky.social",
    "sethrosenthal.bsky.social",
    "jonnichols.bsky.social",
    "spotrac.com",
    "simonpollock.bsky.social",
    "austinkent.bsky.social",
    "talkhoops.bsky.social",
    "nickrestifo.bsky.social",
    "zachlowenba.bsky.social",
    "darthamin.bsky.social",
    "timcato.bsky.social",
    "markdeeks.bsky.social",
    "dannyleroux.bsky.social",
    "andyblarsen.bsky.social",
    "travonne.bsky.social",
    "bullsjay.bsky.social",
    "irawinderman.bsky.social",
    "jamesherbert.bsky.social",
    "teamziller.bsky.social",
    "robmahoney.bsky.social",
    "seeratsohi.bsky.social",
    "kenpom.com",
    "norlander.bsky.social",
    "evanbarnes.bsky.social",
    "yossigozlan.bsky.social",
    "jasmynwimbish.bsky.social",
    "mikefinger.bsky.social",
    "instreetclothes.bsky.social",
    "ryanblackburn.bsky.social",
    "brettdawson.bsky.social",
    "thesteinline.bsky.social",
    "realgmnba.bsky.social",
    "joshrobbins.bsky.social",
    "mirinfader.bsky.social",
    "baxterholmes.bsky.social",
    "tomwesterholm.bsky.social",
    "noadalzell.bsky.social",
    "mikeascotto.bsky.social",
    "aaronbarzilai.bsky.social",
    "marcjspears.bsky.social",
    "tomerazarly.bsky.social",
    "tomhaberstroh.bsky.social",
    "byjayking.bsky.social",
    "mikepradanba.bsky.social",
    "vincegoodwill.bsky.social",
    "samamick.bsky.social",
    "loganmmurdock.bsky.social",
    "jakelfischer.bsky.social",
    "herringnba.bsky.social",
    "louiszatzman.bsky.social",
    "basketball-reference.com",
    "rachel-nichols.bsky.social",
    "samvecenie.bsky.social",
    "johnhollinger.bsky.social",
    "alexkennedynba.bsky.social",
    "jonkrawczynski.bsky.social",
    "masonginsberg.bsky.social",
    "yaronweitzman.bsky.social",
    "keerthikau.bsky.social",
    "bryankalbrosky.bsky.social",
    "keithsmithnba.bsky.social",
    "khobiprice.bsky.social",
    "joeviraynba.bsky.social",
    "jameshamnba.bsky.social",
    "hpbasketball.bsky.social",
    "nbasarah.bsky.social",
    "jasminelwatkins.bsky.social",
    "justesbaraheni.bsky.social",
    "jacobegoldstein.bsky.social",
    "erikg503.bsky.social",
    "mollyhannahm.bsky.social",
    "johnkaralis.com",
    "hoopinformatics.bsky.social",
    "spindavies.bsky.social",
    "willgottlieb.bsky.social",
    "knarsu3.bsky.social",
    "highkin.bsky.social",
    "jacksimone.bsky.social",
    "johngonzalez.bsky.social",
    "nekiasnba.bsky.social",
    "fearthebrown.bsky.social",
    "danwoikesports.bsky.social",
    "ctabatabaie.bsky.social",
    "blakemurphy.bsky.social",
    "paulhudrick.bsky.social",
    "justinquinnn.bsky.social",
    "michaelvpina.bsky.social",
    "jonhamm.bsky.social",
    "kerithburke.bsky.social",
    "jadubin5.bsky.social",
    "adamtaylornba.bsky.social",
    "samdigiovanni.bsky.social",
    "austinkrell.bsky.social",
    "kyleneubeck.bsky.social",
    "geraldbourguet.bsky.social",
    "scooperhoops2.bsky.social",
    "dannycunningham.bsky.social",
    "anthonyirwinla.bsky.social",
    "nbacobwebs.bsky.social",
    "btrowland.bsky.social",
    "msjnba.bsky.social",
    "joelrushnba.bsky.social",
    "ekoreen.bsky.social",
    "mikevorkunov.bsky.social",
    "duncansmith.bsky.social",
    "danfavale.bsky.social",
    "lawmurraythenu.bsky.social",
    "cavsanada.bsky.social",
    "derekbodner.bsky.social",
    "jimowczarski.bsky.social",
    "johnschuhmann.bsky.social",
    "wtevs.bsky.social",
    "stephnoh.bsky.social",
    "basketballtalk.bsky.social",
    "kpelton.bsky.social",
    "yourmandevine.bsky.social",
    "howardbeck.bsky.social",
    "dimeuproxx.bsky.social",
    "shamsbot.bsky.social",
    "hoopshye.bsky.social",
]

BLUESKY_REFRESH_SECONDS = 120        # How often to fetch new posts (2 min)
BLUESKY_MAX_POSTS = 10               # Max posts to display in sidebar
BLUESKY_SHOW_REPOSTS = False         # False = original posts only
BLUESKY_CACHE_TTL_SECONDS = 90       # Cache lifetime before refetch


# ═══════════════════════════════════════
# HEADLINES TICKER (Google Sheets)
# ═══════════════════════════════════════

HEADLINES_SHEET_ID = "13Qj9cjBWjWjBD-1UcP96st1hMc6MDYrCtMrTvdb2NyM"
HEADLINES_SHEET_GID = "950003816"
HEADLINES_COLUMN = "B"                   # Column containing headline text
HEADLINES_REFRESH_SECONDS = 180          # How often to fetch (3 min)
HEADLINES_MAX_ITEMS = 20                 # Max headlines in ticker
HEADLINES_CACHE_TTL_SECONDS = 150        # Cache lifetime
HEADLINES_NEW_COUNT = 5                  # First N headlines get "NEW" badge


# ═══════════════════════════════════════
# LIVE SCORES (Phase 2)
# ═══════════════════════════════════════

SCORES_REFRESH_SECONDS = 30          # Frontend polling interval
SCORES_CACHE_TTL_LIVE = 30           # Cache TTL when live games are active
SCORES_CACHE_TTL_FINAL = 300         # Cache TTL when all games are final (5 min)
SCORES_PRIORITY_TEAMS = []           # e.g. ["LAL", "BOS"] — featured more often
SCORES_SCOREBOARD_URL = "https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json"
SCORES_BOXSCORE_URL = "https://cdn.nba.com/static/json/liveData/boxscore/boxscore_{game_id}.json"


# ═══════════════════════════════════════
# RANKINGS / GOOGLE SHEETS (Phase 3 — not yet active)
# ═══════════════════════════════════════

RANKINGS_SHEETS = [
    # {
    #     "name": "Trade Value Rankings",
    #     "url": "https://docs.google.com/spreadsheets/d/SHEET_ID/gviz/tq?tqx=out:json&sheet=TAB_NAME",
    #     "columns": ["Rank", "Player", "Team", "Trade Value"],
    #     "max_rows": 10,
    # },
]
RANKINGS_ROTATE_SECONDS = 15
RANKINGS_REFRESH_SECONDS = 300


# ═══════════════════════════════════════
# SERVER
# ═══════════════════════════════════════

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 5000
DEBUG = True
